export enum NotificationPurchaseTitle {
  PAYMENT_RECEIVED_TITLE = 'PAYMENT_RECEIVED_TITLE',
  PAYMENT_FAILED_TITLE = 'PAYMENT_FAILED_TITLE',
  INSUFFICIENT_BALANCE_TITLE = 'INSUFFICIENT_BALANCE_TITLE',
}

export enum NotificationPurchaseMessage {
  PAYMENT_FAILED_MESSAGE = 'PAYMENT_FAILED_MESSAGE',
  ONE_MILLION_PANDA_POINTS_ADDED_MESSAGE = 'ONE_MILLION_PANDA_POINTS_ADDED_MESSAGE',
  ALL_LEVELS_OPEN_FOR_30_DAYS_MESSAGE = 'ALL_LEVELS_OPEN_FOR_30_DAYS_MESSAGE',
  ALL_LEVELS_OPEN_FOR_LIFE_TIME_MESSAGE = 'ALL_LEVELS_OPEN_FOR_LIFE_TIME_MESSAGE',
}

export enum NotificationPurchaseType {
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
}

export enum NotificationDestination {
  APP = 'APP',
  WEBSITE = 'WEBSITE',
}
