export enum TypeUserCounter {
  EDUCATION_LESSON_COUNTER = 'EDUCATION_LESSON_COUNTER',
  PUZZLE_LESSON_COUNTER = 'PUZZLE_LESSON_COUNTER',
  ENDGAMES_LESSON_COUNTER = 'ENDGAMES_LESSON_COUNTER',
  ANIMAL_BOT_COUNTER = 'ANIMAL_BOT_COUNTER',
}
