version: "3.7"

services:
  # NATS-Server
  nats-server:
    image: nats:latest
    container_name: nats
    networks:
      - chessmicroservicesnet

  # Gateway-MS
  chess-gateway:
    container_name: chess-gateway
    build:
      context: ./chess-gateway
      dockerfile: Dockerfile.prod
    image: chess-gateway
    ports:
      - ${CHESS_GATEWAY_PORT}:${CHESS_GATEWAY_PORT}
    environment:
      - PORT=${CHESS_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    networks:
      - chessmicroservicesnet

  # Auth-ms
  auth-ms:
    container_name: auth-ms
    build:
      context: ./chess-auth-ms
      dockerfile: Dockerfile.prod
    image: auth-ms
    restart: always
    depends_on: [auth-mariadb]
    environment:
      PORT: ${AUTH_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      AUTH_MARIADB_CONTAINER_NAME: ${AUTH_MARIADB_CONTAINER_NAME}
      AUTH_CONTAINER_NAME: ${AUTH_CONTAINER_NAME}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      AUTH_DB_USERNAME: ${AUTH_DB_USERNAME}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - chessmicroservicesnet

  auth-mariadb:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${AUTH_MARIADB_CONTAINER_NAME:-auth-mariadb}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MARIADB_USER: ${AUTH_DB_USERNAME}
      MARIADB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "63311:3306"
    restart: always
    networks:
      - chessmicroservicesnet
    volumes:
      - ./chess-auth-ms/auth-mysql-data:/var/lib/mysql

networks:
  chessmicroservicesnet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
