version: "3.7"

services:
  # NATS
  nats:
    image: nats:latest
    container_name: nats-test
    networks:
      - chess_testing

  # Gateway-MS
  chess-gateway:
    container_name: chess-gateway-test
    build:
      context: ./chess-gateway
      dockerfile: Dockerfile.test
    image: chess-gateway-test
    ports:
      - ${CHESS_GATEWAY_PORT}:${CHESS_GATEWAY_PORT}
    environment:
      - PORT=${CHESS_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    volumes:
      - ./chess-gateway/public:/usr/src/app/public
    networks:
      - chess_testing

  # Auth-ms
  auth-ms:
    container_name: auth-ms-test
    build:
      context: ./chess-auth-ms
      dockerfile: Dockerfile.test
    image: auth-ms-test
    restart: always
    depends_on: [auth-mariadb]
    environment:
      PORT: ${AUTH_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      AUTH_MARIADB_CONTAINER_NAME: ${AUTH_MARIADB_CONTAINER_NAME}
      AUTH_CONTAINER_NAME: ${AUTH_CONTAINER_NAME}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      AUTH_DB_USERNAME: ${AUTH_DB_USERNAME}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - chess_testing

  lesson-ms:
    container_name: lesson-ms-test
    build:
      context: ./chess-lesson-ms
      dockerfile: Dockerfile.test
    image: lesson-ms-test
    restart: always
    depends_on: [lesson-mariadb]
    environment:
      PORT: ${LESSON_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      LESSON_MARIADB_CONTAINER_NAME: ${LESSON_MARIADB_CONTAINER_NAME}
      LESSON_CONTAINER_NAME: ${LESSON_CONTAINER_NAME}
      LESSON_DB_PORT: ${LESSON_DB_PORT}
      LESSON_DB_HOST: ${LESSON_DB_HOST}
      LESSON_DB_NAME: ${LESSON_DB_NAME}
      LESSON_DB_ROOT_PASSWORD: ${LESSON_DB_ROOT_PASSWORD}
      LESSON_DB_USERNAME: ${LESSON_DB_USERNAME}
      LESSON_DB_PASSWORD: ${LESSON_DB_PASSWORD}
    volumes:
      - ./chess-lesson-ms/files:/usr/src/app/files
    networks:
      - chess_testing

  game-ms:
    container_name: game-ms-test
    build:
      context: ./chess-game-ms
      dockerfile: Dockerfile.test
    image: game-ms-test
    restart: always
    depends_on: [game-mariadb]
    environment:
      PORT: ${GAME_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      GAME_MARIADB_CONTAINER_NAME: ${GAME_MARIADB_CONTAINER_NAME}
      GAME_CONTAINER_NAME: ${GAME_CONTAINER_NAME}
      GAME_DB_PORT: ${GAME_DB_PORT}
      GAME_DB_HOST: ${GAME_DB_HOST}
      GAME_DB_NAME: ${GAME_DB_NAME}
      GAME_DB_ROOT_PASSWORD: ${GAME_DB_ROOT_PASSWORD}
      GAME_DB_USERNAME: ${GAME_DB_USERNAME}
      GAME_DB_PASSWORD: ${GAME_DB_PASSWORD}
    volumes:
      - ./chess-game-ms/files:/usr/src/app/files
    networks:
      - chess_testing

  auth-mariadb:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${AUTH_MARIADB_CONTAINER_NAME:-auth-mariadb-test}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MARIADB_USER: ${AUTH_DB_USERNAME}
      MARIADB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "63321:3306"
    restart: always
    networks:
      - chess_testing
    volumes:
      - ./chess-auth-ms/auth-mysql-data:/var/lib/mysql

  lesson-mariadb:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${LESSON_MARIADB_CONTAINER_NAME:-lesson-mariadb-test}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${LESSON_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LESSON_DB_NAME}
      MARIADB_USER: ${LESSON_DB_USERNAME}
      MARIADB_PASSWORD: ${LESSON_DB_PASSWORD}
    ports:
      - "63322:3306"
    restart: always
    networks:
      - chess_testing
    volumes:
      - ./chess-lesson-ms/lesson-mysql-data:/var/lib/mysql

  game-mariadb:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${GAME_MARIADB_CONTAINER_NAME:-game-mariadb-test}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${GAME_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GAME_DB_NAME}
      MARIADB_USER: ${GAME_DB_USERNAME}
      MARIADB_PASSWORD: ${GAME_DB_PASSWORD}
    ports:
      - "63323:3306"
    restart: always
    networks:
      - chess_testing
    volumes:
      - ./chess-game-ms/game-mysql-data:/var/lib/mysql

networks:
  chess_testing:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
