version: "3.7"

services:
  # NATS
  nats-dev:
    image: nats:latest
    # container_name: nats
    container_name: nats-dev
    # ports:
    #   - 8222:8222
    networks:
      - chess_development

  # Container advisor - google HTTP lightweight metric
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    restart: always
    networks:
      - chess_development

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    privileged: true
    depends_on:
      - cadvisor
    networks:
      - chess_development

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3015:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
      - "./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    depends_on:
      - prometheus
    networks:
      - chess_development

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save 60 1
      --loglevel warning
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - ./redis-data:/data
    networks:
      - chess_development

  # Gateway-MS
  chess-gateway-dev:
    container_name: chess-gateway-dev
    build: ./chess-gateway
    image: chess-gateway-dev # Explicitly setting the image name
    ports:
      - ${CHESS_GATEWAY_PORT}:3000
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./chess-gateway/src:/usr/src/app/src
      - ./chess-gateway/public:/usr/src/app/public
      - ./chess-gateway/uploads:/usr/src/app/uploads
    environment:
      PORT: ${CHESS_GATEWAY_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - chess_development

  # Auth-ms
  auth-ms-dev:
    container_name: chess-auth-ms-dev
    build: ./chess-auth-ms
    image: auth-ms-dev
    ports:
      - ${AUTH_MS_PORT}:3001
    volumes:
      - ./chess-auth-ms/src:/usr/src/app/src
      - ./seed:/usr/src/app/seed
    depends_on: [auth-mariadb-dev]
    command: npm run start:dev
    environment:
      PORT: ${AUTH_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      AUTH_MARIADB_CONTAINER_NAME: ${AUTH_MARIADB_CONTAINER_NAME}
      AUTH_CONTAINER_NAME: ${AUTH_CONTAINER_NAME}
      AUTH_DB_PORT: ${AUTH_DB_PORT}
      AUTH_DB_HOST: ${AUTH_DB_HOST}
      AUTH_DB_NAME: ${AUTH_DB_NAME}
      AUTH_DB_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      AUTH_DB_USERNAME: ${AUTH_DB_USERNAME}
      AUTH_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      WE_CHESS_EMAIL_USERNAME: ${WE_CHESS_EMAIL_USERNAME}
      WE_CHESS_EMAIL_PASSWORD: ${WE_CHESS_EMAIL_PASSWORD}
    networks:
      - chess_development

  lesson-ms-dev:
    container_name: chess-lesson-ms-dev
    build: ./chess-lesson-ms
    image: lesson-ms-dev
    ports:
      - ${LESSON_MS_PORT}:3002
    volumes:
      - ./chess-lesson-ms/src:/usr/src/app/src
      - ./chess-lesson-ms/files:/usr/src/app/files
    depends_on: [lesson-mariadb-dev]
    command: npm run start:dev
    environment:
      PORT: ${LESSON_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      LESSON_MARIADB_CONTAINER_NAME: ${LESSON_MARIADB_CONTAINER_NAME}
      LESSON_CONTAINER_NAME: ${LESSON_CONTAINER_NAME}
      LESSON_DB_PORT: ${LESSON_DB_PORT}
      LESSON_DB_HOST: ${LESSON_DB_HOST}
      LESSON_DB_NAME: ${LESSON_DB_NAME}
      LESSON_DB_ROOT_PASSWORD: ${LESSON_DB_ROOT_PASSWORD}
      LESSON_DB_USERNAME: ${LESSON_DB_USERNAME}
      LESSON_DB_PASSWORD: ${LESSON_DB_PASSWORD}
      TRANSLATION_API_KEY: ${TRANSLATION_API_KEY}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - chess_development

  game-ms-dev:
    container_name: chess-game-ms-dev
    build: ./chess-game-ms
    image: game-ms-dev
    ports:
      - ${GAME_MS_PORT}:3003
    volumes:
      - ./chess-game-ms/src:/usr/src/app/src
      - ./chess-game-ms/files:/usr/src/app/files
    depends_on: [game-mariadb-dev]
    command: npm run start:dev
    environment:
      PORT: ${GAME_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      GAME_MARIADB_CONTAINER_NAME: ${GAME_MARIADB_CONTAINER_NAME}
      GAME_CONTAINER_NAME: ${GAME_CONTAINER_NAME}
      GAME_DB_PORT: ${GAME_DB_PORT}
      GAME_DB_HOST: ${GAME_DB_HOST}
      GAME_DB_NAME: ${GAME_DB_NAME}
      GAME_DB_ROOT_PASSWORD: ${GAME_DB_ROOT_PASSWORD}
      GAME_DB_USERNAME: ${GAME_DB_USERNAME}
      GAME_DB_PASSWORD: ${GAME_DB_PASSWORD}
    networks:
      - chess_development

  payment-ms-dev:
    container_name: chess-payment-ms-dev
    build: ./chess-payment-ms
    image: payment-ms-dev
    ports:
      - ${PAYMENT_MS_PORT}:3004
    volumes:
      - ./chess-payment-ms/src:/usr/src/app/src
    depends_on: [payment-mariadb-dev]
    command: npm run start:dev
    environment:
      PORT: ${PAYMENT_MS_PORT}
      NATS_SERVERS: "${NATS_SERVERS}"
      MARIADB_VERSION: ${MARIADB_VERSION}
      PAYMENT_MARIADB_CONTAINER_NAME: ${PAYMENT_MARIADB_CONTAINER_NAME}
      PAYMENT_CONTAINER_NAME: ${PAYMENT_CONTAINER_NAME}
      PAYMENT_DB_PORT: ${PAYMENT_DB_PORT}
      PAYMENT_DB_HOST: ${PAYMENT_DB_HOST}
      PAYMENT_DB_NAME: ${PAYMENT_DB_NAME}
      PAYMENT_DB_ROOT_PASSWORD: ${PAYMENT_DB_ROOT_PASSWORD}
      PAYMENT_DB_USERNAME: ${PAYMENT_DB_USERNAME}
      PAYMENT_DB_PASSWORD: ${PAYMENT_DB_PASSWORD}
      STRIPE_SECRET_API_KEY: ${STRIPE_SECRET_API_KEY}
      STRIPE_SUCCESS_URL: ${STRIPE_SUCCESS_URL}
      STRIPE_CANCEL_URL: ${STRIPE_CANCEL_URL}
      STRIPE_ENDPOINT_SECRET: ${STRIPE_ENDPOINT_SECRET}
    networks:
      - chess_development

  auth-mariadb-dev:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${AUTH_MARIADB_CONTAINER_NAME:-auth-mariadb-dev}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MARIADB_USER: ${AUTH_DB_USERNAME}
      MARIADB_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "63311:3306"
    networks:
      - chess_development
    volumes:
      - ./chess-auth-ms/auth-mysql-data:/var/lib/mysql

  lesson-mariadb-dev:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${LESSON_MARIADB_CONTAINER_NAME:-lesson-mariadb-dev}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${LESSON_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${LESSON_DB_NAME}
      MARIADB_USER: ${LESSON_DB_USERNAME}
      MARIADB_PASSWORD: ${LESSON_DB_PASSWORD}
    ports:
      - "63312:3306"
    networks:
      - chess_development
    volumes:
      - ./chess-lesson-ms/lesson-mysql-data:/var/lib/mysql

  game-mariadb-dev:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${GAME_MARIADB_CONTAINER_NAME:-game-mariadb-dev}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${GAME_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GAME_DB_NAME}
      MARIADB_USER: ${GAME_DB_USERNAME}
      MARIADB_PASSWORD: ${GAME_DB_PASSWORD}
    ports:
      - "63313:3306"
    networks:
      - chess_development
    volumes:
      - ./chess-game-ms/game-mysql-data:/var/lib/mysql

  payment-mariadb-dev:
    image: "mariadb:${MARIADB_VERSION:-10.11.2}"
    container_name: ${PAYMENT_MARIADB_CONTAINER_NAME:-payment-mariadb-dev}
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PAYMENT_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PAYMENT_DB_NAME}
      MARIADB_USER: ${PAYMENT_DB_USERNAME}
      MARIADB_PASSWORD: ${PAYMENT_DB_PASSWORD}
    ports:
      - "63314:3306"
    networks:
      - chess_development
    volumes:
      - ./chess-payment-ms/payment-mysql-data:/var/lib/mysql

networks:
  chess_development:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"

volumes:
  grafana-data:
