import type { Metadata } from "next"
import "./globals.css"
import SessionLayout from "@/components/layouts/session"
import localFont from "next/font/local"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "We Chess",
  description: "Generated by create next app",
}

const Rubik = localFont({
  src: "../public/fonts/Rubik.ttf",
})

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body className={cn(Rubik.className, `antialiased`)}>
        <SessionLayout>{children}</SessionLayout>
      </body>
    </html>
  )
}

export default RootLayout
