import { BotDifficulty } from 'src/enum';
import { IBotSeedData } from '../interfaces/bot.interface';

export const botsDataSeed: IBotSeedData[] = [
  // BEGINNER
  {
    animal: 'Mouse',
    name: 'Tik',
    elo: 200,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 5,
  },
  {
    animal: 'Snail',
    name: 'Shelly',
    elo: 250,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 10,
  },
  {
    animal: 'Chick',
    name: 'PiU',
    elo: 300,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 15,
  },
  {
    animal: 'Frog',
    name: 'Kva-Kva',
    elo: 350,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 20,
  },
  {
    animal: 'Bee',
    name: 'Zhu',
    elo: 400,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 25,
  },
  {
    animal: 'Duck',
    name: 'Ducky',
    elo: 450,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 30,
  },
  {
    animal: 'Rabbit',
    name: 'Hooper',
    elo: 500,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 35,
  },
  {
    animal: 'Goat',
    name: 'Archi',
    elo: 550,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 40,
  },
  {
    animal: 'Hippo',
    name: 'Gloria',
    elo: 600,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 45,
  },
  {
    animal: 'Hedgehog',
    name: 'Mimi',
    elo: 650,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 50,
  },
  {
    animal: 'Hamster',
    name: 'Toto',
    elo: 700,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 55,
  },
  {
    animal: 'Rooster',
    name: 'Pecko',
    elo: 750,
    difficulty: BotDifficulty.BEGINNER,
    pointsWhenWin: 60,
  },
  // CASUAL
  {
    animal: 'Squirrel',
    name: 'Crispy',
    elo: 800,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 65,
  },
  {
    animal: 'Turtle',
    name: 'Turta',
    elo: 850,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 70,
  },
  {
    animal: 'Raccoon',
    name: 'Noko',
    elo: 900,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 75,
  },
  {
    animal: 'Cat',
    name: 'Tom',
    elo: 1000,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 80,
  },
  {
    animal: 'Owl',
    name: 'Oona',
    elo: 1100,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 85,
  },
  {
    animal: 'Beaver',
    name: 'Beebo',
    elo: 1200,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 90,
  },
  {
    animal: 'Parrot',
    name: 'Paco',
    elo: 1300,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 95,
  },
  {
    animal: 'Monkey',
    name: 'Tata',
    elo: 1400,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 100,
  },
  {
    animal: 'Fox',
    name: 'Roxy',
    elo: 1500,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 105,
  },
  {
    animal: 'Elephant',
    name: 'Ellie',
    elo: 1600,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 110,
  },
  {
    animal: 'Dolphin',
    name: 'Finn',
    elo: 1700,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 115,
  },
  {
    animal: 'Snake',
    name: 'Zina',
    elo: 1800,
    difficulty: BotDifficulty.CASUAL,
    pointsWhenWin: 120,
  },
  // INTERMEDIATE
  {
    animal: 'Wolf',
    name: 'Conan',
    elo: 2000,
    difficulty: BotDifficulty.INTERMEDIATE,
    pointsWhenWin: 125,
  },
  {
    animal: 'Tiger',
    name: 'Aurora',
    elo: 2200,
    difficulty: BotDifficulty.INTERMEDIATE,
    pointsWhenWin: 135,
  },
  // MASTER
  {
    animal: 'Eagle',
    name: 'Gabriel',
    elo: 2300,
    difficulty: BotDifficulty.MASTER,
    pointsWhenWin: 140,
  },
  {
    animal: 'Dragon',
    name: 'Thandor',
    elo: 2400,
    difficulty: BotDifficulty.MASTER,
    pointsWhenWin: 145,
  },
  // GRAND_MASTER
  {
    animal: 'Greazly Bear',
    name: 'Boss',
    elo: 2500,
    difficulty: BotDifficulty.GRAND_MASTER,
    pointsWhenWin: 150,
  },
  {
    animal: 'Panda',
    name: 'Great Sensei Panda',
    elo: 2700,
    difficulty: BotDifficulty.GRAND_MASTER,
    pointsWhenWin: 155,
  },
];
