import { LessonNameAsBot, LessonNameAsGame } from 'src/enum';
import { ILessonParentSeed } from '../interfaces';

// these enums has to be equal to translate keys on flutter app
enum LessonParentTranslateGameName {
  TETRIS_GAME = 'TETRIS_GAME',
  GUESS_SQUARE_GAME = 'GUESS_SQUARE_GAME',
  RIGHT_PIECE_ON_RIGHT_SQUARE_GAME = 'RIGHT_PIECE_ON_RIGHT_SQUARE_GAME',
  MEMORY_TESTER_GAME = 'MEMORY_TESTER_GAME',
}

export const lessonParentDataSeed: ILessonParentSeed[] = [
  // EDUCATION
  {
    timer: 0,
    name: LessonNameAsGame.TETRIS_GAME,
    nameTr: LessonParentTranslateGameName.TETRIS_GAME,
    levelTr: 'Game',
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 2, // complete Level 2 of Tetris game
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: 'reach_level_3_tetris_message',
  },
  {
    timer: 30,
    name: 'pawn',
    nameTr: 'pawn',
    levelTr: 'level1',
    pgnFilename: 'Level_1_Pawn.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'king',
    nameTr: 'king',
    levelTr: 'level1',
    pgnFilename: 'Level_1_King.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'bishop',
    nameTr: 'bishop',
    levelTr: 'level1',
    pgnFilename: 'Level_1_Bishop.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'knight',
    nameTr: 'knight',
    levelTr: 'level1',
    pgnFilename: 'Level_1_Knight.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'rook',
    nameTr: 'rook',
    levelTr: 'level1',
    pgnFilename: 'Level_1_Rook.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'queen',
    nameTr: 'queen',
    levelTr: 'level1',
    pgnFilename: 'Level_1_Queen.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 1',
    nameTr: 'test1',
    levelTr: 'level1',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Castle',
    nameTr: 'castle',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Preview_1_Castle.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Give check to the King',
    nameTr: 'give_check_to_the_king',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Preview_2_Give_check_to_the_king.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Pawn promotion',
    nameTr: 'pawn_promotion',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Preview_3_Pawn_promotion.pgn',
    lessonFactor: 0.625,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/8
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Stalemate',
    nameTr: 'stalemate',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Preview_4_Stalemate.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Take en passant',
    nameTr: 'take_en_passant',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Preview_5_Take_en_passant.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Take with a pawn',
    nameTr: 'take_with_a_pawn',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Preview_6_Take_with_a_pawn.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Move + Check + Take',
    nameTr: 'move_check_take',
    levelTr: 'level2',
    pgnFilename: 'Level_2_Move_Check_Take.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 2',
    nameTr: 'test2',
    levelTr: 'level2',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'What is a mate',
    nameTr: 'what_is_a_mate',
    levelTr: 'level3',
    pgnFilename: 'Level_3_Preview_1_What_is_a_mate.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 3',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Checkmate with doublecheck',
    nameTr: 'checkmate_with_doublecheck',
    levelTr: 'level3',
    pgnFilename: 'Level_3_Preview_2_Checkmate_with_doublecheck.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 3',
    showHint: true,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Checkmate using the pin',
    nameTr: 'checkmate_using_the_pin',
    levelTr: 'level3',
    pgnFilename: 'Level_3_Preview_3_Checkmate_using_the_pin.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 3',
    showHint: true,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Mate in One',
    nameTr: 'mate_in_one',
    levelTr: 'level3',
    pgnFilename: 'Level_3_Mate_in_1.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 3',
    nameTr: 'test3',
    levelTr: 'level3',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.GUESS_SQUARE_GAME,
    nameTr: LessonParentTranslateGameName.GUESS_SQUARE_GAME,
    levelTr: 'Game',
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 2, // complete Level 3 of Guess the square game
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: 'reach_level_3_guess_square_message',
  },
  {
    timer: 120,
    name: 'The King',
    nameTr: 'the_king',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Preview_1_The_king.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Queen',
    nameTr: 'the_queen',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Preview_2_The_queen.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Rook',
    nameTr: 'the_rook',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Preview_3_The_rook.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Bishop',
    nameTr: 'the_bishop',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Preview_4_The_bishop.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Knight',
    nameTr: 'the_knight',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Preview_5_The_knight.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Pawn',
    nameTr: 'the_pawn',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Preview_6_The_pawn.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Win a piece in one move',
    nameTr: 'win_a_piece_in_one_move',
    levelTr: 'level4',
    pgnFilename: 'Level_4_Win_a_piece_in_1_move.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 4',
    nameTr: 'test4',
    levelTr: 'level4',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'Complicated checkmate',
    nameTr: 'complicated_checkmate',
    levelTr: 'level5',
    pgnFilename: 'Level_5_Complicated_checkmate.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 5',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 5',
    nameTr: 'test5',
    levelTr: 'level5',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 5',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'Pin + Win material in one move',
    nameTr: 'pin_win_material_in_one_move',
    levelTr: 'level6',
    pgnFilename: 'Level_6_Pin_Win_Material_in_1_move.pgn',
    lessonFactor: 0.039,
    story: 'Education',
    level: 'Level 6',
    quantityToUnlockNext: 10, // 10/252
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 6',
    nameTr: 'test6',
    levelTr: 'level6',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 6',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsBot.DEFEAT_TO_TIK_AND_SHELLY,
    nameTr: 'defeat_to_tik_and_shelly',
    levelTr: 'play_chess',
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Play chess',
    quantityToUnlockNext: 2, // defeat bot N1 and N2
    levelFrontend: 'Play chess',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: true,
    canBeSkipped: false,
    messageModal:
      'Play chess against Tik and Shelly animal and defeat them. Go to Plays screen and complete the mission to unlock Level 7. Good luck!',
  },
  {
    timer: 60,
    name: 'Smothered mate',
    nameTr: 'smothered_mate',
    levelTr: 'level7',
    pgnFilename: 'Level_7_Preview_1_Smothered_mate.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Stalemate Level 7',
    nameTr: 'stalemate_level_7',
    levelTr: 'level7',
    pgnFilename: 'Level_7_Preview_2_Stalemate.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 7',
    showHint: true,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Mate in 2 moves',
    nameTr: 'mate_in_2_moves',
    levelTr: 'level7',
    pgnFilename: 'Level_7_Mate_in_2_moves.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 7',
    nameTr: 'test7',
    levelTr: 'level7',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Difficult mate in 2 moves',
    nameTr: 'difficult_mate_in_2_moves',
    levelTr: 'level8',
    pgnFilename: 'Level_8_Difficult_mate_in_2_moves.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 8',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 8,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 8',
    nameTr: 'test8',
    levelTr: 'level8',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 8',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.RIGHT_PIECE_ON_RIGHT_SQUARE_GAME,
    nameTr: LessonParentTranslateGameName.RIGHT_PIECE_ON_RIGHT_SQUARE_GAME,
    levelTr: 'game',
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 2, // complete Level 2 of Right piece on right square
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: 'reach_level_3_piece_plus_square_message',
  },
  {
    timer: 75,
    name: 'Double attack',
    nameTr: 'double_attack',
    levelTr: 'level9',
    pgnFilename: 'Level_9_Preview_1_Double_attack.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'Skewer',
    nameTr: 'skewer',
    levelTr: 'level9',
    pgnFilename: 'Level_9_Preview_2_Skewer.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'The Pin',
    nameTr: 'the_pin',
    levelTr: 'level9',
    pgnFilename: 'Level_9_Preview_3_The_pin.pgn',
    lessonFactor: 0.125,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 5, // 5/40
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'Material Win',
    nameTr: 'material_win',
    levelTr: 'level9',
    pgnFilename: 'Level_9_Material_win.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'test 9',
    nameTr: 'test9',
    levelTr: 'level9',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.MEMORY_TESTER_GAME,
    nameTr: LessonParentTranslateGameName.MEMORY_TESTER_GAME,
    levelTr: 'game',
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 2, // complete Level 3 of Memory Tester
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: 'reach_level_3_memory_tester_wc_message',
  },
  {
    timer: 75,
    name: 'Mate in many moves',
    nameTr: 'mate_in_many_moves',
    levelTr: 'level10',
    pgnFilename: 'Level_10_Difficult_mate_in_many_moves.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 10',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 10',
    showHint: false,
    pointsPerLesson: 10,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'test 10',
    nameTr: 'test10',
    levelTr: 'level10',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 10',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 10',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  // PUZZLE
  {
    timer: 30,
    name: 'Winning combination',
    nameTr: 'winning_combination',
    levelTr: 'level1',
    pgnFilename: 'Level_11_Puzzle_Winning_combination.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 1',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 1',
    nameTr: 'test1',
    levelTr: 'level1',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Great moves',
    nameTr: 'great_moves',
    levelTr: 'level2',
    pgnFilename: 'Level_12_Puzzle_Great_moves.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 2',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 2',
    nameTr: 'test2',
    levelTr: 'level2',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Master of the motives',
    nameTr: 'master_of_the_motives',
    levelTr: 'level3',
    pgnFilename: 'Level_13_Puzzle_Master_of_the_motives.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 3',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 3',
    nameTr: 'test3',
    levelTr: 'level3',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'The wizard',
    nameTr: 'the_wizard',
    levelTr: 'level4',
    pgnFilename: 'Level_14_Puzzle_The_wizard.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 4',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 4',
    nameTr: 'test4',
    levelTr: 'level4',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 4',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'Big brain',
    nameTr: 'big_brain',
    levelTr: 'level5',
    pgnFilename: 'Level_15_Puzzle_Big_brain.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 5',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 5',
    nameTr: 'test5',
    levelTr: 'level5',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 5',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Mastermind solver',
    nameTr: 'mastermind_solver',
    levelTr: 'level6',
    pgnFilename: 'Level_16_Puzzle_Mastermind_solver.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 6',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 6',
    nameTr: 'test6',
    levelTr: 'level6',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 6',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'ASAP',
    nameTr: 'asap',
    levelTr: 'level7',
    pgnFilename: 'Level_17_Puzzle_Asap.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 7',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 7',
    nameTr: 'test7',
    levelTr: 'level7',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 7',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'The master of studies',
    nameTr: 'the_master_of_studies',
    levelTr: 'level8',
    pgnFilename: 'Level_18_Puzzle_The_master_of_studies.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 8',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 8,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 8',
    nameTr: 'test8',
    levelTr: 'level8',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 8',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'The boss',
    nameTr: 'the_boss',
    levelTr: 'level9',
    pgnFilename: 'Level_19_Puzzle_The_boss.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 9',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 9',
    nameTr: 'test9',
    levelTr: 'level9',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 9',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  // Endgame
  {
    timer: 90,
    name: 'Pawn Endgame',
    nameTr: 'pawn_endgame',
    levelTr: 'level1',
    pgnFilename: 'Level_20_Endgame_Pawn.pgn',
    lessonFactor: 0.28,
    story: 'Endgame',
    level: 'Level 1',
    quantityToUnlockNext: 20, // 20/69
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 1',
    nameTr: 'test1',
    levelTr: 'level1',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'Knight Endgame',
    nameTr: 'knight_endgame',
    levelTr: 'level2',
    pgnFilename: 'Level_21_Endgame_Knight.pgn',
    lessonFactor: 0.18,
    story: 'Endgame',
    level: 'Level 2',
    quantityToUnlockNext: 20, // 20/111
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 2',
    nameTr: 'test2',
    levelTr: 'level2',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'Bishop Endgame',
    nameTr: 'bishop_endgame',
    levelTr: 'level3',
    pgnFilename: 'Level_22_Endgame_Bishop.pgn',
    lessonFactor: 0.14,
    story: 'Endgame',
    level: 'Level 3',
    quantityToUnlockNext: 20, // 20/142
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 3',
    nameTr: 'test3',
    levelTr: 'level3',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'Bishop and Knight Endgame',
    nameTr: 'bishop_and_knight_endgame',
    levelTr: 'level4',
    pgnFilename: 'Level_23_Endgame_Bishop_And_Knight.pgn',
    lessonFactor: 0.12,
    story: 'Endgame',
    level: 'Level 4',
    quantityToUnlockNext: 20, // 20/162
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 4',
    nameTr: 'test4',
    levelTr: 'level4',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 4',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'Rook Endgame',
    nameTr: 'rook_endgame',
    levelTr: 'level5',
    pgnFilename: 'Level_24_Endgame_Rook.pgn',
    lessonFactor: 0.13,
    story: 'Endgame',
    level: 'Level 5',
    quantityToUnlockNext: 20, // 20/152
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 5',
    nameTr: 'test5',
    levelTr: 'level5',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 5',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'Rook and Minor Piece',
    nameTr: 'rook_and_minor_piece',
    levelTr: 'level6',
    pgnFilename: 'Level_25_Endgame_Rook_And_Minor_Piece.pgn',
    lessonFactor: 0.078,
    story: 'Endgame',
    level: 'Level 6',
    quantityToUnlockNext: 20, // 20/255
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 6',
    nameTr: 'test6',
    levelTr: 'level6',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 6',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'Queen Endgame',
    nameTr: 'queen_endgame',
    levelTr: 'level7',
    pgnFilename: 'Level_26_Endgame_Queen.pgn',
    lessonFactor: 0.869,
    story: 'Endgame',
    level: 'Level 7',
    quantityToUnlockNext: 20, // 20/23
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 7',
    nameTr: 'test7',
    levelTr: 'level7',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Endgame',
    level: 'Level 7',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
];
