import { LessonNameAsGame } from 'src/enum';
import { ILessonParentSeed } from '../interfaces';

export const lessonParentDataSeed: ILessonParentSeed[] = [
  // EDUCATION
  {
    timer: 0,
    name: LessonNameAsGame.TETRIS_GAME,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: LessonNameAsGame.TETRIS_GAME,
    quantityToUnlockNext: 3, // complete Level 3 of Tetris game
    levelFrontend: LessonNameAsGame.TETRIS_GAME,
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    messageModal:
      'Reach at least Level 3 in Tetris game to unlock Level 1. Good luck!',
  },
  {
    timer: 30,
    name: 'pawn',
    pgnFilename: 'Level_1_Pawn.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'king',
    pgnFilename: 'Level_1_King.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'bishop',
    pgnFilename: 'Level_1_Bishop.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'knight',
    pgnFilename: 'Level_1_Knight.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'rook',
    pgnFilename: 'Level_1_Rook.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'queen',
    pgnFilename: 'Level_1_Queen.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 1',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Castle',
    pgnFilename: 'Level_2_Preview_1_Castle.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Give check to the King',
    pgnFilename: 'Level_2_Preview_2_Give_check_to_the_king.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Pawn promotion',
    pgnFilename: 'Level_2_Preview_3_Pawn_promotion.pgn',
    lessonFactor: 0.625,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/8
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Stalemate',
    pgnFilename: 'Level_2_Preview_4_Stalemate.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Take en passant',
    pgnFilename: 'Level_2_Preview_5_Take_en_passant.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Take with a pawn',
    pgnFilename: 'Level_2_Preview_6_Take_with_a_pawn.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Move + Check + Take',
    pgnFilename: 'Level_2_Move_Check_Take.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 2',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 1,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'What is a mate',
    pgnFilename: 'Level_3_Preview_1_What_is_a_mate.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Checkmate with doublecheck',
    pgnFilename: 'Level_3_Preview_2_Checkmate_with_doublecheck.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Checkmate using the pin',
    pgnFilename: 'Level_3_Preview_3_Checkmate_using_the_pin.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Mate in One',
    pgnFilename: 'Level_3_Mate_in_1.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 3',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 1,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.GUESS_SQUARE_GAME,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: LessonNameAsGame.GUESS_SQUARE_GAME,
    quantityToUnlockNext: 3, // complete Level 3 of Guess the square game
    levelFrontend: LessonNameAsGame.GUESS_SQUARE_GAME,
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    messageModal:
      'Reach at least Level 3 in Guess the square game to unlock Level 4. Good luck!',
  },
  // TODO: continue with remains Education levels
  // PUZZLE
  // {
  //   timer: 30,
  //   name: 'Winning combination',
  //   pgnFilename: 'Level_4_Puzzle_Winning_combination.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 4',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 1',
  //   showHint: false,
  //   pointsPerLesson: 1,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 30,
  //   name: 'test 1',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 4',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 1',
  //   showHint: false,
  //   pointsPerLesson: 1,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 30,
  //   name: 'Great moves',
  //   pgnFilename: 'Level_5_Puzzle_Great_moves.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 5',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 2',
  //   showHint: false,
  //   pointsPerLesson: 2,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 30,
  //   name: 'test 2',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 5',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 2',
  //   showHint: false,
  //   pointsPerLesson: 2,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 30,
  //   name: 'Master of the motives',
  //   pgnFilename: 'Level_6_Puzzle_Master_of_the_motives.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 6',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 3',
  //   showHint: false,
  //   pointsPerLesson: 3,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 30,
  //   name: 'test 3',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 6',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 3',
  //   showHint: false,
  //   pointsPerLesson: 3,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 45,
  //   name: 'The wizard',
  //   pgnFilename: 'Level_7_Puzzle_The_wizard.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 7',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 4',
  //   showHint: false,
  //   pointsPerLesson: 4,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 45,
  //   name: 'test 4',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 7',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 4',
  //   showHint: false,
  //   pointsPerLesson: 4,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 45,
  //   name: 'Big brain',
  //   pgnFilename: 'Level_8_Puzzle_Big_brain.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 8',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 5',
  //   showHint: false,
  //   pointsPerLesson: 5,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 45,
  //   name: 'test 5',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 8',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 5',
  //   showHint: false,
  //   pointsPerLesson: 5,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 60,
  //   name: 'Mastermind solver',
  //   pgnFilename: 'Level_9_Puzzle_Mastermind_solver.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 9',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 6',
  //   showHint: false,
  //   pointsPerLesson: 6,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 60,
  //   name: 'test 6',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 9',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 6',
  //   showHint: false,
  //   pointsPerLesson: 6,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 60,
  //   name: 'ASAP',
  //   pgnFilename: 'Level_10_Puzzle_Asap.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 10',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 7',
  //   showHint: false,
  //   pointsPerLesson: 7,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 60,
  //   name: 'test 7',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 10',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 7',
  //   showHint: false,
  //   pointsPerLesson: 7,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 90,
  //   name: 'The master of studies',
  //   pgnFilename: 'Level_11_Puzzle_The_master_of_studies.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 11',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 8',
  //   showHint: false,
  //   pointsPerLesson: 8,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 90,
  //   name: 'test 8',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 11',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 8',
  //   showHint: false,
  //   pointsPerLesson: 8,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 90,
  //   name: 'The boss',
  //   pgnFilename: 'Level_12_Puzzle_The_boss.pgn',
  //   lessonFactor: 0.08,
  //   story: 'Puzzle',
  //   level: 'Level 12',
  //   quantityToUnlockNext: 20, // 20/250
  //   levelFrontend: 'Level 9',
  //   showHint: false,
  //   pointsPerLesson: 9,
  //   isTest: false,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
  // {
  //   timer: 90,
  //   name: 'test 9',
  //   pgnFilename: null,
  //   lessonFactor: 0.7,
  //   story: 'Puzzle',
  //   level: 'Level 12',
  //   quantityToUnlockNext: 7, // 7/10
  //   levelFrontend: 'Level 9',
  //   showHint: false,
  //   pointsPerLesson: 9,
  //   isTest: true,
  //   isGame: false,
  //   isPreview: false,
  //   isBot: false,
  //   messageModal: null,
  // },
];
