export const lessonParentEducationPuzzleDataSeed = [
  // EDUCATION
  {
    timer: 30,
    name: 'pawn',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'king',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'bishop',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'knight',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'rook',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'queen',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'test 1',
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: true,
  },
  {
    timer: 30,
    name: 'level 2',
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 50, // 50/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'test 2',
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 1,
    isTest: true,
  },
  {
    timer: 30,
    name: 'Mate in One',
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 50, // 50/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'test 3',
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 1,
    isTest: true,
  },

  // PUZZLE
  {
    timer: 30,
    name: 'Winning combination',
    story: 'Puzzle',
    level: 'Level 4',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 1,
    isTest: false,
  },
  {
    timer: 30,
    name: 'test 1',
    story: 'Puzzle',
    level: 'Level 4',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 1,
    isTest: true,
  },
  {
    timer: 30,
    name: 'Great moves',
    story: 'Puzzle',
    level: 'Level 5',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
  },
  {
    timer: 30,
    name: 'test 2',
    story: 'Puzzle',
    level: 'Level 5',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: true,
  },
  {
    timer: 30,
    name: 'Master of the motives',
    story: 'Puzzle',
    level: 'Level 6',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
  },
  {
    timer: 30,
    name: 'test 3',
    story: 'Puzzle',
    level: 'Level 6',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: true,
  },
  {
    timer: 45,
    name: 'The wizard',
    story: 'Puzzle',
    level: 'Level 7',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: false,
  },
  {
    timer: 45,
    name: 'test 4',
    story: 'Puzzle',
    level: 'Level 7',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: true,
  },
  {
    timer: 45,
    name: 'Big brain',
    story: 'Puzzle',
    level: 'Level 8',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: false,
  },
  {
    timer: 45,
    name: 'test 5',
    story: 'Puzzle',
    level: 'Level 8',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: true,
  },
  {
    timer: 60,
    name: 'Mastermind solver',
    story: 'Puzzle',
    level: 'Level 9',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: false,
  },
  {
    timer: 60,
    name: 'test 6',
    story: 'Puzzle',
    level: 'Level 9',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: true,
  },
  {
    timer: 60,
    name: 'ASAP',
    story: 'Puzzle',
    level: 'Level 10',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
  },
  {
    timer: 60,
    name: 'test 7',
    story: 'Puzzle',
    level: 'Level 10',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: true,
  },
  {
    timer: 90,
    name: 'The master of studies',
    story: 'Puzzle',
    level: 'Level 11',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 8,
    isTest: false,
  },
  {
    timer: 90,
    name: 'test 8',
    story: 'Puzzle',
    level: 'Level 11',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 8,
    isTest: true,
  },
  {
    timer: 90,
    name: 'The boss',
    story: 'Puzzle',
    level: 'Level 12',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
  },
  {
    timer: 90,
    name: 'test 9',
    story: 'Puzzle',
    level: 'Level 12',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: true,
  },
];
