import { LessonNameAsBot, LessonNameAsGame } from 'src/enum';
import { ILessonParentSeed } from '../interfaces';

export const lessonParentDataSeed: ILessonParentSeed[] = [
  // EDUCATION
  {
    timer: 0,
    name: LessonNameAsGame.TETRIS_GAME,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 3, // complete Level 3 of Tetris game
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal:
      'Reach at least Level 3 in Tetris game to unlock Level 1. Good luck!',
  },
  {
    timer: 30,
    name: 'pawn',
    pgnFilename: 'Level_1_Pawn.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'king',
    pgnFilename: 'Level_1_King.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'bishop',
    pgnFilename: 'Level_1_Bishop.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'knight',
    pgnFilename: 'Level_1_Knight.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'rook',
    pgnFilename: 'Level_1_Rook.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'queen',
    pgnFilename: 'Level_1_Queen.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 10, // 10/20
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 1',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: true,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Castle',
    pgnFilename: 'Level_2_Preview_1_Castle.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Give check to the King',
    pgnFilename: 'Level_2_Preview_2_Give_check_to_the_king.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Pawn promotion',
    pgnFilename: 'Level_2_Preview_3_Pawn_promotion.pgn',
    lessonFactor: 0.625,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/8
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Stalemate',
    pgnFilename: 'Level_2_Preview_4_Stalemate.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Take en passant',
    pgnFilename: 'Level_2_Preview_5_Take_en_passant.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Take with a pawn',
    pgnFilename: 'Level_2_Preview_6_Take_with_a_pawn.pgn',
    lessonFactor: 0.5,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 5, // 5/10
    levelFrontend: 'Level 2',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Move + Check + Take',
    pgnFilename: 'Level_2_Move_Check_Take.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 2',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'What is a mate',
    pgnFilename: 'Level_3_Preview_1_What_is_a_mate.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 3',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Checkmate with doublecheck',
    pgnFilename: 'Level_3_Preview_2_Checkmate_with_doublecheck.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 3',
    showHint: true,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Checkmate using the pin',
    pgnFilename: 'Level_3_Preview_3_Checkmate_using_the_pin.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 3',
    showHint: true,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Mate in One',
    pgnFilename: 'Level_3_Mate_in_1.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 3',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.GUESS_SQUARE_GAME,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 3, // complete Level 3 of Guess the square game
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal:
      'Reach at least Level 3 in Guess the square game to unlock Level 4. Good luck!',
  },
  {
    timer: 120,
    name: 'The King',
    pgnFilename: 'Level_4_Preview_1_The_king.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Queen',
    pgnFilename: 'Level_4_Preview_2_The_queen.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Rook',
    pgnFilename: 'Level_4_Preview_3_The_rook.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Bishop',
    pgnFilename: 'Level_4_Preview_4_The_bishop.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Knight',
    pgnFilename: 'Level_4_Preview_5_The_knight.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 120,
    name: 'The Pawn',
    pgnFilename: 'Level_4_Preview_6_The_pawn.pgn',
    lessonFactor: 1,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 1, // 1/1
    levelFrontend: 'Level 4',
    showHint: true,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: true,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Win a piece in one move',
    pgnFilename: 'Level_4_Win_a_piece_in_1_move.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 4',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 4',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'Complicated checkmate',
    pgnFilename: 'Level_5_Complicated_checkmate.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 5',
    quantityToUnlockNext: 10, // 10/250
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 5',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 5',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'Pin + Win material in one move',
    pgnFilename: 'Level_6_Pin_Win_Material_in_1_move.pgn',
    lessonFactor: 0.039,
    story: 'Education',
    level: 'Level 6',
    quantityToUnlockNext: 10, // 10/252
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 6',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 6',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsBot.DEFEAT_TO_TIK_AND_SHELLY,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Play chess',
    quantityToUnlockNext: 2, // defeat bot N1 and N2
    levelFrontend: 'Play chess',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: true,
    canBeSkipped: false,
    messageModal:
      'Play chess against Tik and Shelly animal and defeat them. Go to Plays screen and complete the mission to unlock Level 7. Good luck!',
  },
  {
    timer: 60,
    name: 'Smothered mate',
    pgnFilename: 'Level_7_Preview_1_Smothered_mate.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Stalemate Level 7',
    pgnFilename: 'Level_7_Preview_2_Stalemate.pgn',
    lessonFactor: 0.119,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 5, // 5/42
    levelFrontend: 'Level 7',
    showHint: true,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Mate in 2 moves',
    pgnFilename: 'Level_7_Mate_in_2_moves.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 5, // 10/250
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 7',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 7',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Difficult mate in 2 moves',
    pgnFilename: 'Level_8_Difficult_mate_in_2_moves.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 8',
    quantityToUnlockNext: 5, // 10/250
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 8,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 8',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 8',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.RIGHT_PIECE_ON_RIGHT_SQUARE_GAME,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 3, // complete Level 3 of Right piece on right square
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal:
      'Reach at least Level 3 in Right piece on right square game to unlock Level 9. Good luck!',
  },
  {
    timer: 75,
    name: 'Double attack',
    pgnFilename: 'Level_9_Preview_1_Double_attack.pgn',
    lessonFactor: 0.25,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 10, // 10/40
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'Skewer',
    pgnFilename: 'Level_9_Preview_2_Skewer.pgn',
    lessonFactor: 0.25,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 10, // 10/40
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'The Pin',
    pgnFilename: 'Level_9_Preview_3_The_pin.pgn',
    lessonFactor: 0.25,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 10, // 10/40
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: true,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'Material Win',
    pgnFilename: 'Level_9_Material_win.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 5, // 10/250
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'test 9',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 9',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 0,
    name: LessonNameAsGame.MEMORY_TESTER_GAME,
    pgnFilename: null,
    lessonFactor: 0,
    story: 'Education',
    level: 'Game',
    quantityToUnlockNext: 3, // complete Level 3 of Memory Tester
    levelFrontend: 'Game',
    showHint: false,
    pointsPerLesson: 0,
    isTest: false,
    isGame: true,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal:
      'Reach at least Level 3 in Memory Tester game to unlock Level 10. Good luck!',
  },
  {
    timer: 75,
    name: 'Mate in many moves',
    pgnFilename: 'Level_10_Difficult_mate_in_many_moves.pgn',
    lessonFactor: 0.04,
    story: 'Education',
    level: 'Level 10',
    quantityToUnlockNext: 5, // 10/250
    levelFrontend: 'Level 10',
    showHint: false,
    pointsPerLesson: 10,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 75,
    name: 'test 10',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Education',
    level: 'Level 10',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 10',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  // PUZZLE
  {
    timer: 30,
    name: 'Winning combination',
    pgnFilename: 'Level_11_Puzzle_Winning_combination.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 1',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 1,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 1',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 1',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 1',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Great moves',
    pgnFilename: 'Level_12_Puzzle_Great_moves.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 2',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 2,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 2',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 2',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 2',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'Master of the motives',
    pgnFilename: 'Level_13_Puzzle_Master_of_the_motives.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 3',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 3,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 30,
    name: 'test 3',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 3',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 3',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'The wizard',
    pgnFilename: 'Level_14_Puzzle_The_wizard.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 4',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 4,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 4',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 4',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 4',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'Big brain',
    pgnFilename: 'Level_15_Puzzle_Big_brain.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 5',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 5,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 45,
    name: 'test 5',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 5',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 5',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'Mastermind solver',
    pgnFilename: 'Level_16_Puzzle_Mastermind_solver.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 6',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 6,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 6',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 6',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 6',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'ASAP',
    pgnFilename: 'Level_17_Puzzle_Asap.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 7',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 7,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 60,
    name: 'test 7',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 7',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 7',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'The master of studies',
    pgnFilename: 'Level_18_Puzzle_The_master_of_studies.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 8',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 8,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 8',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 8',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 8',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'The boss',
    pgnFilename: 'Level_19_Puzzle_The_boss.pgn',
    lessonFactor: 0.08,
    story: 'Puzzle',
    level: 'Level 9',
    quantityToUnlockNext: 20, // 20/250
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 9,
    isTest: false,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
  {
    timer: 90,
    name: 'test 9',
    pgnFilename: null,
    lessonFactor: 0.7,
    story: 'Puzzle',
    level: 'Level 9',
    quantityToUnlockNext: 7, // 7/10
    levelFrontend: 'Level 9',
    showHint: false,
    pointsPerLesson: 0,
    isTest: true,
    isGame: false,
    isPreview: false,
    isBot: false,
    canBeSkipped: false,
    messageModal: null,
  },
];
